CREATE OR REPLACE SEMANTIC VIEW COLM_DB.STRUCTURED.SP500
    TABLES (COLM_DB.STRUCTURED.SP500_COMPANIES)
    FACTS (
        SP500_COMPANIES.CURRENTPRICE AS CURRENTPRICE,
        SP500_COMPANIES.REVENUEGROWTH AS REVENUEGROWTH
    )
    DIMENSIONS (
        SP500_COMPANIES.SYMBOL AS SYMBOL,
        SP500_COMPANIES.SHORTNAME AS SHORTNAME,
        SP500_COMPANIES.LONGNAME AS LONGNAME,
        SP500_COMPANIES.SECTOR AS SECTOR,
        SP500_COMPANIES.INDUSTRY AS INDUSTRY,
        SP500_COMPANIES.MARKETCAP AS MARKETCAP,
        SP500_COMPANIES.EBITDA AS EBITDA,
        SP500_COMPANIES.CITY AS CITY,
        SP500_COMPANIES.STATE AS STATE,
        SP500_COMPANIES.COUNTRY AS COUNTRY,
        SP500_COMPANIES.FULLTIMEEMPLOYEES AS FULLTIMEEMPLOYEES,
        SP500_COMPANIES.LONGBUSINESSSUMMARY AS LONGBUSINESSSUMMARY,
        SP500_COMPANIES.WEIGHT AS WEIGHT
    );
